---
- name: Ensure required packages are installed
  action: "{{ package_info.pkg_mgr }}"
  args: package_info.args
  with_items: "{{ package_info.sprk_pkgs }}"
  when: package_info.sprk_pkgs|length > 0

- name: templated spark params for ambari service
  template: src=spark-params.j2 dest=/var/lib/ambari-server/resources/stacks/HDP/{{ hdp_version }}/services/SPARKS/package/scripts/params.py

- name: templated tachyon master for ambari service
  template: src=tachyon-master.j2 dest=/var/lib/ambari-server/resources/stacks/HDP/{{ hdp_version }}/services/TACHYON/package/scripts/master.py

- name: templated tachyon params for ambari service
  template: src=tachyon-params.j2 dest=/var/lib/ambari-server/resources/stacks/HDP/{{ hdp_version }}/services/TACHYON/package/scripts/params.py
