---

#- name: Install CentOS repo.
#  yum:
#    name: "{{ centos_repo_url }}"
#    state: present
#  register: result
#  until: '"failed" not in result'
#  retries: 5
#  delay: 10
#
#- name: Import CentOS GPG key.
#  rpm_key: 
#    key: "{{ centos_repo_gpg_key_url }}"
#    state: present

  - name: install Repos 
    yum: "name={{ item }} state=installed"
    register: result
    until: '"failed" not in result'
    retries: 5
    delay: 10
    with_items:
    - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    - "http://mirror.centos.org/centos/7.2.1511/os/x86_64/Packages/centos-release-7-2.1511.el7.centos.2.10.x86_64.rpm"

- name: Import GPG keys
  rpm_key: "key={{ item }} state=present"
  with_items:
  -  "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7"
  -  "/etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7"


